### ISSUE TITLE
Ionic / Cordova installation should include cordova-annotated-plugin-android

### ISSUE THREAD

**Issue by earslap** [RevenueCat/cordova-plugin-purchases#112] opened 2021-11-07 22:12 UTC
- [X] I have updated Purchases SDK to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/RevenueCat/cordova-plugin-purchases/blob/main/CONTRIBUTING.md)
- [X] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [X] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [X] I have searched for [existing Github issues](https://github.com/RevenueCat/cordova-plugin-purchases/issues)

**Describe the bug**
This is not a huge deal but the documentation doesn't mention it for installation: during `ionic cap sync android`, the sync process complains about the lack of `cordova-annotated-plugin-android` package and directs you to install it through `npm install` which works, and then sync works without issues. Maybe should be added to the documentation or direct dependencies?

**Comment by JazmineMT** [comment] 2021-11-10 22:41
Hi @earslap, 

Thank you for bringing this to our attention! We can update the docs to reflect this. We reserve our Github issues for bugs found in our SDKs. This type of question would be great for your community where a support engineer can assist you for future reference. You can ask this question here: https://community.revenuecat.com/.

Thanks and have a great week!

**Comment by paulovargatt** [comment] 2022-05-16 21:23
Same problem
![image](https://user-images.githubusercontent.com/28814403/168684797-9cba7cea-6f18-4693-9d2a-984e95945190.png)

**Comment by eikaramba** [comment] 2022-07-13 16:26
this is still the case? why was it closed ?

**Comment by vegaro** [comment] 2022-07-15 17:49
I just tested it and I could reproduce it.

I opened https://github.com/RevenueCat/cordova-plugin-purchases/pull/152 which I think fixes it. Just tested it by pointing to the branch directly and it looks like it works as it should.

Sorry for closing this in the past

**Comment by vegaro** [comment] 2022-07-18 08:08
We merged the fix for the package.json missing the dependency and this is fixed in the latest release `3.0.0-rc.1`

**Closed by vegaro** 2022-07-18 08:08 UTC
Labels: bug, status: needs-additional-info
