### ISSUE TITLE
Capacitor 3.0 iOS API request completed with status: POST /v1/subscribers//attributes 404

### ISSUE THREAD

**Issue by Yuripetusko** [RevenueCat/cordova-plugin-purchases#89] opened 2021-06-07 11:44 UTC
- [x] I have updated Purchases SDK to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/RevenueCat/cordova-plugin-purchases/blob/develop/CONTRIBUTING.md)
- [x] I have read the [Help Center](https://support.revenuecat.com/hc/en-us)
- [x] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [x] I have searched for [existing Github issues](https://github.com/RevenueCat/cordova-plugin-purchases/issues)

**Describe the bug**
A clear and concise description of what the bug is. The more detail you can provide the faster our team will be able to triage and resolve the issue. If debug logs are not applicable to this issue, please do not remove step 2 when submitting the issue.

1. Environment
   1. Platform: Capacitor 3.0.0
   2. SDK version: 2.1.1
   3. OS + version: iOS 14.4.2
   4. XCode/Android Studio version: Xcode 12.5
   5. Framework (Cordova, Ionic, Ionic Native, etc): Capacitor
   6. Framework version: 3.0.0
   7. How widespread is the issue. Percentage of devices affected.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
```
2021-06-07 13:19:23.088502+0100 App[8931:4393582] [Purchases] - DEBUG: 😻 Subscriber attributes synced successfully for App User ID: PWreTVIxQZhvCY0E2LoLcewhKQy1
2021-06-07 13:19:23.088872+0100 App[8931:4393582] [Purchases] - DEBUG: ℹ️ Serial request done: POST /subscribers/PWreTVIxQZhvCY0E2LoLcewhKQy1/attributes, 0 requests left in the queue
2021-06-07 13:19:53.280125+0100 App[8931:4393606] [tcp] tcp_input [C11.1:3] flags=[R] seq=2081823440, ack=0, win=0 state=LAST_ACK rcv_nxt=2081823440, snd_una=2973302146
2021-06-07 13:19:53.281300+0100 App[8931:4393606] [tcp] tcp_input [C11.1:3] flags=[R] seq=2081823440, ack=0, win=0 state=CLOSED rcv_nxt=2081823440, snd_una=2973302146
2021-06-07 13:19:53.281758+0100 App[8931:4393606] [tcp] tcp_input [C11.1:3] flags=[R] seq=2081823440, ack=0, win=0 state=CLOSED rcv_nxt=2081823440, snd_una=2973302146
2021-06-07 13:19:56.071894+0100 App[8931:4391239] [Purchases] - DEBUG: ℹ️ applicationDidBecomeActive
2021-06-07 13:19:56.091634+0100 App[8931:4393572] [Purchases] - DEBUG: ℹ️ There are no requests currently running, starting request POST /subscribers//attributes
2021-06-07 13:19:56.091731+0100 App[8931:4393572] [Purchases] - DEBUG: ℹ️ API request started: POST /v1/subscribers//attributes
2021-06-07 13:19:57.114815+0100 App[8931:4393734] [Purchases] - DEBUG: ℹ️ API request completed with status: POST /v1/subscribers//attributes 404
2021-06-07 13:19:57.115108+0100 App[8931:4393734] [Purchases] - ERROR: 😿‼️ Unknown error.
2021-06-07 13:19:57.115427+0100 App[8931:4393734] [Purchases] - ERROR: 😿‼️ Error when syncing subscriber attributes. Details: Unknown error.
 UserInfo:{
    NSLocalizedDescription = "Unknown error.";
    NSUnderlyingError = "Error Domain=RCBackendErrorDomain Code=7117 \"Page not found.\" UserInfo={NSLocalizedDescription=Page not found.}";
    "readable_error_code" = UNKNOWN;
    successfullySynced = 0;
}
```
3. Steps to reproduce, with a description of expected vs. actual behavior
When in sandbox mode, wait until subscription is expired, and then re-subscribe again. I get this error consistently
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)

**Additional context**
Can this double slash be a problem? And why is there a double forward slash
POST /v1/subscribers//attributes

**Comment by Yuripetusko** [comment] 2021-06-07 12:05
It seems like userId is not picked to be put in POST request `/v1/subscribers//attributes` but identify call was successful so user should be set

**Comment by Yuripetusko** [comment] 2021-06-07 12:22
Looks like it correctly uses user id on first request, but subsequent request doesn't use user id

```
2021-06-07 13:19:23.088502+0100 App[8931:4393582] [Purchases] - DEBUG: 😻 Subscriber attributes synced successfully for App User ID: PWreTVIxQZhvCY0E2LoLcewhKQy1
2021-06-07 13:19:23.088872+0100 App[8931:4393582] [Purchases] - DEBUG: ℹ️ Serial request done: POST /subscribers/PWreTVIxQZhvCY0E2LoLcewhKQy1/attributes, 0 requests left in the queue
2021-06-07 13:19:53.280125+0100 App[8931:4393606] [tcp] tcp_input [C11.1:3] flags=[R] seq=2081823440, ack=0, win=0 state=LAST_ACK rcv_nxt=2081823440, snd_una=2973302146
2021-06-07 13:19:53.281300+0100 App[8931:4393606] [tcp] tcp_input [C11.1:3] flags=[R] seq=2081823440, ack=0, win=0 state=CLOSED rcv_nxt=2081823440, snd_una=2973302146
2021-06-07 13:19:53.281758+0100 App[8931:4393606] [tcp] tcp_input [C11.1:3] flags=[R] seq=2081823440, ack=0, win=0 state=CLOSED rcv_nxt=2081823440, snd_una=2973302146
2021-06-07 13:19:56.071894+0100 App[8931:4391239] [Purchases] - DEBUG: ℹ️ applicationDidBecomeActive
2021-06-07 13:19:56.091634+0100 App[8931:4393572] [Purchases] - DEBUG: ℹ️ There are no requests currently running, starting request POST /subscribers//attributes
2021-06-07 13:19:56.091731+0100 App[8931:4393572] [Purchases] - DEBUG: ℹ️ API request started: POST /v1/subscribers//attributes
2021-06-07 13:19:57.114815+0100 App[8931:4393734] [Purchases] - DEBUG: ℹ️ API request completed with status: POST /v1/subscribers//attributes 404
2021-06-07 13:19:57.115108+0100 App[8931:4393734] [Purchases] - ERROR: 😿‼️ Unknown error.
2021-06-07 13:19:57.115427+0100 App[8931:4393734] [Purchases] - ERROR: 😿‼️ Error when syncing subscriber attributes. Details: Unknown error.
 UserInfo:{
    NSLocalizedDescription = "Unknown error.";
    NSUnderlyingError = "Error Domain=RCBackendErrorDomain Code=7117 \"Page not found.\" UserInfo={NSLocalizedDescription=Page not found.}";
    "readable_error_code" = UNKNOWN;
    successfullySynced = 0;
}
```

**Comment by Yuripetusko** [comment] 2021-06-07 13:12
Looks like this is what happens, while native iOS purchase dialog appears, my app gets suspended in the background due to memory use

```
Received memory pressure event 2 vm pressure 0
2021-06-07 14:10:01.194678+0100 App[9049:4400953] [tcp] tcp_input [C10.1:3] flags=[R] seq=962722545, ack=0, win=0 state=LAST_ACK rcv_nxt=962722545, snd_una=236610892
2021-06-07 14:10:01.195149+0100 App[9049:4400953] [tcp] tcp_input [C10.1:3] flags=[R] seq=962722545, ack=0, win=0 state=CLOSED rcv_nxt=962722545, snd_una=236610892
2021-06-07 14:10:01.195224+0100 App[9049:4400953] [tcp] tcp_input [C10.1:3] flags=[R] seq=962722545, ack=0, win=0 state=CLOSED rcv_nxt=962722545, snd_una=236610892
```

then when I enter my sandbox login details and make a purchase I receive 

```
DEBUG: ℹ️ applicationDidBecomeActive
2021-06-07 14:10:22.689184+0100 App[9049:4401063] [Purchases] - DEBUG: ℹ️ There are no requests currently running, starting request POST /subscribers//attributes
```

So when app is restored, userId context is lost

**Comment by beylmk** [comment] 2021-06-07 17:09
@Yuripetusko thanks for the issue report and for all the detailed logs! Are you clearing your NSUserDefaults at any point, perhaps on app backgrounding? This would clear our user ID from the cache, causing the problem above.

Either way, we should be checking for empty userId before calling POST /v1/subscribers/{userId}/attributes so that we can provide a more specific error.

**Comment by Yuripetusko** [comment] 2021-06-14 14:42
Thanks @beylmk I am not clearing anything intentionally but ios might because our react/capacitor app uses quite a lot of memory and when debugging it locally and looking at xcode debugging logs then it uses even more memory, so sometimes it restarts to release some of that locked memory. (only happens localy. So this could be related 🤔

**Comment by Yuripetusko** [comment] 2021-06-14 14:45
Actually it also happens in production

**Comment by aboedo** [comment] 2021-06-14 15:07
Hey @Yuripetusko, 

>  Can this double slash be a problem? And why is there a double forward slash

Well, that double slash is happening because somehow the SDK is missing the `appUserID` - the URL is supposed to be `/v1/subscribers/<user_id>/attributes`. 
This is why we were asking about potentially having `userDefaults` erased - that's where the `appUserID` is currently stored. 

`UserDefaults` don't live in memory but rather in a file, so they shouldn't get lost if your app is closed. However, if your app gets killed because the OS thinks it's using too much memory, I think there's a chance that `UserDefaults` don't get synced in time before the app dies. 

Is this something that you can reproduce consistently? 

First, can you make absolutely sure that there isn't anything in the app erasing `UserDefaults`?
If there's nothing, then, you should try to figure out why the memory warnings are coming - is the app using too much memory? If so, the OS will give your app a chance to save stuff before it gets killed, [more info here](https://developer.apple.com/documentation/uikit/app_and_environment/managing_your_app_s_life_cycle/responding_to_memory_warnings). You can use [plugins like this one](https://www.npmjs.com/package/cordova-plugin-memory-warning) to respond in such an event to save stuff to disk.

**Comment by taquitos** [comment] 2021-10-14 18:07
With RCv4, this situation is no longer possible. We're currently in beta. We'll work on back porting this fix 👍

**Comment by riderx** [comment] 2022-03-02 17:47
@Yuripetusko i made a capacitor version of this plugin with RCv4 in iOS : https://github.com/riderx/capacitor-purchases

**Comment by taquitos** [comment] 2022-08-01 17:47
RCv4 has been out for a while, we haven't received any more reports of this issue so I'm going to close this out. If you encounter this again, definitely let us know by opening a new issue! Thank you again for taking the time to report and work with us 😄

**Closed by taquitos** 2022-08-01 17:47 UTC
Labels: bug, triaged
