### ISSUE TITLE
Cannot resolve symbol 'hybridcommon' on Android

### ISSUE THREAD

**Issue by mansourcodes** [RevenueCat/cordova-plugin-purchases#142] opened 2022-07-04 08:40 UTC
- [ Yes ] I have updated Purchases SDK to the latest version
- [ Yes ] I have read the [Contribution Guidelines](https://github.com/RevenueCat/cordova-plugin-purchases/blob/main/CONTRIBUTING.md)
- [ Yes  ] I have searched the [Community](https://community.revenuecat.com)
 https://community.revenuecat.com/sdks-51/ionic-failed-to-build-android-app-cannot-resolve-symbol-hybridcommon-and-more-1783?postid=5538#post5538
- [ Yes] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [ Yes] I have searched for [existing Github issues](https://github.com/RevenueCat/cordova-plugin-purchases/issues)

**Describe the bug**

I have installed cordova and capacitor plugins for ionic by following this guide :

https://ionicframework.com/docs/native/purchases

```
$ npm install cordova-plugin-purchases@2.3.0 
$ npm install @awesome-cordova-plugins/purchases 
$ ionic cap sync
```

package.json I have those :

```
"@awesome-cordova-plugins/core": "5.43.0",
"@awesome-cordova-plugins/purchases": "^5.44.0",
"cordova-annotated-plugin-android": "^1.0.4",
"cordova-plugin-purchases": "^2.3.0",
```

**Then when I run the android studio this missing libraries shows:** 
Cannot resolve symbol 'hybridcommon'
Cannot resolve symbol 'common'
Cannot resolve symbol 'interfaces'
Cannot resolve symbol 'PlatformInfo'
Cannot resolve symbol 'CommonKt'
Cannot resolve symbol 'Purchases'
Cannot resolve symbol 'UpdatedPurchaserInfoListener'
Cannot resolve symbol 'PurchaserInfoMapperKt'

All those files found in this repo : 
https://github.com/RevenueCat/purchases-hybrid-common
but on the Doc (https://docs.revenuecat.com/docs/getting-started) 
there is no mention to how to add it ?

<img width="1064" alt="Screen Shot 2022-07-03 at 4 24 17 PM" src="https://user-images.githubusercontent.com/3064487/177116723-ca1f34f6-f705-4fc4-94db-25bfddcfe086.png">

1. Environment
   1. Platform: android
   2. SDK version:
   3. OS + version:
   4. XCode/Android Studio version: Android Studio Arctic Fox | 2020.3.1 Patch 4
   5. Framework (Cordova, Ionic, Ionic Native, etc): Ionic
   6. Framework version: Ionic 6
   7. How widespread is the issue. Percentage of devices affected.
2. [Debug logs](https://docs.revenuecat.com/docs/debugging) that reproduce the issue
3. Steps to reproduce, with a description of expected vs. actual behavior
4. **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc.)
5. 
https://community.revenuecat.com/sdks-51/ionic-failed-to-build-android-app-cannot-resolve-symbol-hybridcommon-and-more-1783?postid=5538#post5538

**Additional context**

**Comment by aboedo** [comment] 2022-07-04 15:42
Hi! 👋 thanks for reporting! 

It looks like somehow the Android dependency wasn't picked up correctly. 
I'll dig in today and try to reproduce. 

In the meantime, just to check, if you go into Android studio and go to File -> `sync project with Gradle files`, do you get any errors or does it run correctly?

**Comment by aboedo** [comment] 2022-07-04 18:40
I just tried installing on a new app and wasn't able to reproduce this issue. 

Could you try: 
- `ionic capacitor update`
- `ionic cap sync`
- go to Android Studio -> File -> `sync project with Gradle files`

And see if that helps?

**Comment by mansourcodes** [comment] 2022-07-04 19:36
Thanks, Solved with:
```
Android Studio -> File -> sync project with Gradle files
```

Suggest add it on the Documentation : https://docs.revenuecat.com/docs/ionic

**Comment by aboedo** [comment] 2022-07-04 19:37
@mansourcodes will do! Thanks for reporting back!

**Comment by aboedo** [comment] 2022-07-04 19:39
Added!

**Comment by aboedo** [comment] 2022-07-07 19:28
I'm closing this issue for now, but let us know if you run into any more issues!!

**Closed by aboedo** 2022-07-07 19:28 UTC
Labels: bug
